/*
 * generated by Xtext
 */
package at.bestsolution.lego.ui.contentassist

import at.bestsolution.lego.ui.contentassist.AbstractLegoProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class LegoProposalProvider extends AbstractLegoProposalProvider {
}
