/*
* generated by Xtext
*/
package at.bestsolution.lego.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bestsolution.lego.services.LegoGrammarAccess;

public class LegoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LegoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.bestsolution.lego.parser.antlr.internal.InternalLegoParser createParser(XtextTokenStream stream) {
		return new at.bestsolution.lego.parser.antlr.internal.InternalLegoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public LegoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LegoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
