/*
* generated by Xtext
*/
package at.bestsolution.lego.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import at.bestsolution.lego.services.LegoGrammarAccess;

public class LegoParser extends AbstractContentAssistParser {
	
	@Inject
	private LegoGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected at.bestsolution.lego.ui.contentassist.antlr.internal.InternalLegoParser createParser() {
		at.bestsolution.lego.ui.contentassist.antlr.internal.InternalLegoParser result = new at.bestsolution.lego.ui.contentassist.antlr.internal.InternalLegoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getAlternatives(), "rule__Model__Alternatives");
					put(grammarAccess.getLegoElementAccess().getAlternatives(), "rule__LegoElement__Alternatives");
					put(grammarAccess.getRasterItemAccess().getAlternatives(), "rule__RasterItem__Alternatives");
					put(grammarAccess.getRepostoryItemAccess().getAlternatives(), "rule__RepostoryItem__Alternatives");
					put(grammarAccess.getSourceAccess().getAlternatives(), "rule__Source__Alternatives");
					put(grammarAccess.getAssemblyItemAccess().getAlternatives(), "rule__AssemblyItem__Alternatives");
					put(grammarAccess.getRasterAssemblyItemAccess().getTransformAlternatives_5_1_0(), "rule__RasterAssemblyItem__TransformAlternatives_5_1_0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getItemRepositoryAccess().getGroup(), "rule__ItemRepository__Group__0");
					put(grammarAccess.getMountedPartAccess().getGroup(), "rule__MountedPart__Group__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getBrickAccess().getGroup(), "rule__Brick__Group__0");
					put(grammarAccess.getGeneratedAccess().getGroup(), "rule__Generated__Group__0");
					put(grammarAccess.getGeneratedAccess().getGroup_1(), "rule__Generated__Group_1__0");
					put(grammarAccess.getGeneratedAccess().getGroup_1_4(), "rule__Generated__Group_1_4__0");
					put(grammarAccess.getFxmlIncludeAccess().getGroup(), "rule__FxmlInclude__Group__0");
					put(grammarAccess.getFxmlIncludeAccess().getGroup_2(), "rule__FxmlInclude__Group_2__0");
					put(grammarAccess.getAssemblyAccess().getGroup(), "rule__Assembly__Group__0");
					put(grammarAccess.getRasterAssemblyItemAccess().getGroup(), "rule__RasterAssemblyItem__Group__0");
					put(grammarAccess.getRasterAssemblyItemAccess().getGroup_5(), "rule__RasterAssemblyItem__Group_5__0");
					put(grammarAccess.getMountedAssemblyItemAccess().getGroup(), "rule__MountedAssemblyItem__Group__0");
					put(grammarAccess.getMountedAssemblyItemAccess().getGroup_5(), "rule__MountedAssemblyItem__Group_5__0");
					put(grammarAccess.getModelAccess().getRepoAssignment_0(), "rule__Model__RepoAssignment_0");
					put(grammarAccess.getModelAccess().getAssemblyAssignment_1(), "rule__Model__AssemblyAssignment_1");
					put(grammarAccess.getItemRepositoryAccess().getNameAssignment_0(), "rule__ItemRepository__NameAssignment_0");
					put(grammarAccess.getItemRepositoryAccess().getElementListAssignment_2(), "rule__ItemRepository__ElementListAssignment_2");
					put(grammarAccess.getMountedPartAccess().getNameAssignment_1(), "rule__MountedPart__NameAssignment_1");
					put(grammarAccess.getMountedPartAccess().getFillAssignment_2(), "rule__MountedPart__FillAssignment_2");
					put(grammarAccess.getMountedPartAccess().getSourceAssignment_3(), "rule__MountedPart__SourceAssignment_3");
					put(grammarAccess.getColorAccess().getRAssignment_1(), "rule__Color__RAssignment_1");
					put(grammarAccess.getColorAccess().getGAssignment_2(), "rule__Color__GAssignment_2");
					put(grammarAccess.getColorAccess().getBAssignment_3(), "rule__Color__BAssignment_3");
					put(grammarAccess.getXUnitAccess().getUnitsAssignment(), "rule__XUnit__UnitsAssignment");
					put(grammarAccess.getYUnitAccess().getUnitsAssignment(), "rule__YUnit__UnitsAssignment");
					put(grammarAccess.getZUnitAccess().getUnitsAssignment(), "rule__ZUnit__UnitsAssignment");
					put(grammarAccess.getBrickAccess().getNameAssignment_1(), "rule__Brick__NameAssignment_1");
					put(grammarAccess.getBrickAccess().getXUnitsAssignment_3(), "rule__Brick__XUnitsAssignment_3");
					put(grammarAccess.getBrickAccess().getYUnitsAssignment_4(), "rule__Brick__YUnitsAssignment_4");
					put(grammarAccess.getBrickAccess().getZUnitsAssignment_5(), "rule__Brick__ZUnitsAssignment_5");
					put(grammarAccess.getBrickAccess().getFillAssignment_6(), "rule__Brick__FillAssignment_6");
					put(grammarAccess.getBrickAccess().getSourceAssignment_7(), "rule__Brick__SourceAssignment_7");
					put(grammarAccess.getGeneratedAccess().getWidthAssignment_1_1(), "rule__Generated__WidthAssignment_1_1");
					put(grammarAccess.getGeneratedAccess().getHeightAssignment_1_2(), "rule__Generated__HeightAssignment_1_2");
					put(grammarAccess.getGeneratedAccess().getDepthAssignment_1_3(), "rule__Generated__DepthAssignment_1_3");
					put(grammarAccess.getGeneratedAccess().getOriginXAssignment_1_4_1(), "rule__Generated__OriginXAssignment_1_4_1");
					put(grammarAccess.getGeneratedAccess().getOriginYAssignment_1_4_2(), "rule__Generated__OriginYAssignment_1_4_2");
					put(grammarAccess.getGeneratedAccess().getOriginZAssignment_1_4_3(), "rule__Generated__OriginZAssignment_1_4_3");
					put(grammarAccess.getFxmlIncludeAccess().getSource3dAssignment_1(), "rule__FxmlInclude__Source3dAssignment_1");
					put(grammarAccess.getFxmlIncludeAccess().getOriginXAssignment_2_1(), "rule__FxmlInclude__OriginXAssignment_2_1");
					put(grammarAccess.getFxmlIncludeAccess().getOriginYAssignment_2_2(), "rule__FxmlInclude__OriginYAssignment_2_2");
					put(grammarAccess.getFxmlIncludeAccess().getOriginZAssignment_2_3(), "rule__FxmlInclude__OriginZAssignment_2_3");
					put(grammarAccess.getAssemblyAccess().getNameAssignment_1(), "rule__Assembly__NameAssignment_1");
					put(grammarAccess.getAssemblyAccess().getItemsAssignment_3(), "rule__Assembly__ItemsAssignment_3");
					put(grammarAccess.getRasterAssemblyItemAccess().getElementAssignment_0(), "rule__RasterAssemblyItem__ElementAssignment_0");
					put(grammarAccess.getRasterAssemblyItemAccess().getXUnitsAssignment_2(), "rule__RasterAssemblyItem__XUnitsAssignment_2");
					put(grammarAccess.getRasterAssemblyItemAccess().getYUnitsAssignment_3(), "rule__RasterAssemblyItem__YUnitsAssignment_3");
					put(grammarAccess.getRasterAssemblyItemAccess().getZUnitsAssignment_4(), "rule__RasterAssemblyItem__ZUnitsAssignment_4");
					put(grammarAccess.getRasterAssemblyItemAccess().getTransformAssignment_5_1(), "rule__RasterAssemblyItem__TransformAssignment_5_1");
					put(grammarAccess.getMountedAssemblyItemAccess().getElementAssignment_0(), "rule__MountedAssemblyItem__ElementAssignment_0");
					put(grammarAccess.getMountedAssemblyItemAccess().getXUnitsAssignment_2(), "rule__MountedAssemblyItem__XUnitsAssignment_2");
					put(grammarAccess.getMountedAssemblyItemAccess().getYUnitsAssignment_3(), "rule__MountedAssemblyItem__YUnitsAssignment_3");
					put(grammarAccess.getMountedAssemblyItemAccess().getZUnitsAssignment_4(), "rule__MountedAssemblyItem__ZUnitsAssignment_4");
					put(grammarAccess.getMountedAssemblyItemAccess().getRotateXAssignment_5_1(), "rule__MountedAssemblyItem__RotateXAssignment_5_1");
					put(grammarAccess.getMountedAssemblyItemAccess().getRotateYAssignment_5_2(), "rule__MountedAssemblyItem__RotateYAssignment_5_2");
					put(grammarAccess.getMountedAssemblyItemAccess().getRotateZAssignment_5_3(), "rule__MountedAssemblyItem__RotateZAssignment_5_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			at.bestsolution.lego.ui.contentassist.antlr.internal.InternalLegoParser typedParser = (at.bestsolution.lego.ui.contentassist.antlr.internal.InternalLegoParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public LegoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LegoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
