/*
 * generated by Xtext
 */
package at.bestsolution.lego;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LegoRuntimeModule extends at.bestsolution.lego.AbstractLegoRuntimeModule {

}
