/*
* generated by Xtext
*/
package at.bestsolution.lego;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class LegoUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.bestsolution.lego.ui.internal.LegoActivator.getInstance().getInjector("at.bestsolution.lego.Lego");
	}
	
}
