/*
 * generated by Xtext
 */
package at.bestsolution.lego.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import at.bestsolution.lego.ui.internal.LegoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LegoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LegoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LegoActivator.getInstance().getInjector(LegoActivator.AT_BESTSOLUTION_LEGO_LEGO);
	}
	
}
