/*
 * generated by Xtext
 */
package at.bestsolution.lego.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LegoUiModule extends at.bestsolution.lego.ui.AbstractLegoUiModule {
	public LegoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
